services:
  web:
    build:
      context: .
    image: host
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
    env_file:
      - .env
  postgres:
    container_name: ${POSTGRES_HOST}
    image: 'postgres'
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - ./docker/db-data/:/var/lib/postgresql/data/
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
  dashboard:
    image: illasoft/illa-builder
    container_name: illa-builder
    ports:
      - "8080:2022"
      # - "443:443"
    restart: unless-stopped