services:
  web:
    build:
      context: .
    image: host
    ports:
      - '3000:3000'
    volumes:
      - .:/app
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
    env_file:
      - .env
  postgres:
    container_name: ${POSTGRES_HOST}
    image: 'postgres'
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - ./docker/db-data/:/var/lib/postgresql/data/
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 8080:80
    env_file:
      - .env
    depends_on:
      - postgres